spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/
    username: postgres
    password: 15935746
  jpa:
    show-sql: true
    generate-ddl: true
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    properties:
      hibernate:
        ddl-auto: create-drop
        format_sql: true
        tmp.use_jdbc_metadata_defaults: false
        jdbc.lob.non_contextual_creation: true